<?php

include('class.views.php');
include('template/parser/class.parser.php');
include('template/class.template.php');
include('template/task/class.task.php');
include('template/task/taskscomparison/class.taskscomparison.php');
include('template/task/taskstag/class.taskstag.php');
include('template/logic/ilogic/class.ilogic.php');
include('template/logic/class.logic.php');
include('template/logic/logicloop/class.logicloop.php');
include('template/logic/logiccomparison/class.logiccomparison.php');
include('template/logic/logictpl/class.logictpl.php');
include('template/logic/logicnoparse/class.logicnoparse.php');
include('template/logic/logichref/class.logichref.php');
include('template/logic/logicif/class.logicif.php');
include('template/logic/logicconst/class.logicconst.php');
include('template/logic/logicvar/class.logicvar.php');
include('template/logic/logicinclude/class.logicinclude.php');
include('template/tag/class.tag.php');
include('template/viewbag/class.viewbag.php');